version: '3.8'

services:
  bulletjournaldb:
    image: postgres:latest
    environment:
      POSTGRES_DB: bulletjournaldb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  pgdata: