# Utilisez l'image Docker officielle PostgreSQL comme base
FROM postgres:latest

# Définissez les variables d'environnement pour la base de données PostgreSQL
ENV POSTGRES_DB=bulletjournaldb
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=mypassword

# Exposez le port par défaut de PostgreSQL (5432)
EXPOSE 5432